read_utf8_lines <- function(path) {
  readLines(path, warn = FALSE, encoding = "UTF-8")
}

yaml_block <- function(path) {
  lines <- read_utf8_lines(path)
  if (length(lines) < 3 || lines[[1]] != "---") {
    stop(path, " must start with YAML frontmatter.", call. = FALSE)
  }

  closing <- which(lines[-1] == "---")
  if (length(closing) == 0) {
    stop(path, " has unclosed YAML frontmatter.", call. = FALSE)
  }

  list(
    frontmatter = lines[2:closing[[1]]],
    body = lines[seq.int(closing[[1]] + 2, length(lines))]
  )
}

yaml_paths <- function(frontmatter, path) {
  paths_index <- which(trimws(frontmatter) == "paths:")
  if (length(paths_index) != 1) {
    stop(path, " must define exactly one paths list.", call. = FALSE)
  }

  candidates <- frontmatter[seq.int(paths_index + 1, length(frontmatter))]
  path_lines <- candidates[grepl("^\\s*-\\s+", candidates)]
  values <- sub("^\\s*-\\s+", "", path_lines)
  sub("^(['\"])(.*)\\1$", "\\2", trimws(values))
}

yaml_value <- function(frontmatter, field, path) {
  matches <- grep(paste0("^", field, "\\s*:"), frontmatter, value = TRUE)
  if (length(matches) != 1) {
    stop(path, " must define exactly one '", field, "' field.", call. = FALSE)
  }

  value <- trimws(sub("^[^:]+:\\s*", "", matches[[1]]))
  sub("^(['\"])(.*)\\1$", "\\2", value)
}

yaml_quote <- function(value) {
  paste0('"', gsub('"', '\\"', value, fixed = TRUE), '"')
}

rule_title <- function(body, path) {
  headings <- body[grepl("^# ", body)]
  if (length(headings) == 0) {
    stop(path, " must contain a level-one heading.", call. = FALSE)
  }
  sub("^# ", "", headings[[1]])
}

render_github_rule <- function(rule_path) {
  rule <- yaml_block(rule_path)
  paths <- yaml_paths(rule$frontmatter, rule_path)
  name <- basename(rule_path)
  title <- rule_title(rule$body, rule_path)

  c(
    "---",
    paste0("applyTo: ", yaml_quote(paste(paths, collapse = ","))),
    "---",
    "",
    paste0("# ", title),
    "",
    paste0(
      "Before changing a matched file, read and follow the canonical ",
      "[", name, "](../../.claude/rules/", name, ")."
    ),
    "",
    "This file is generated by `tools/generate-agent-adapters.R`; do not edit it directly."
  )
}

render_cursor_rule <- function(rule_path) {
  rule <- yaml_block(rule_path)
  paths <- yaml_paths(rule$frontmatter, rule_path)
  name <- basename(rule_path)
  title <- rule_title(rule$body, rule_path)

  c(
    "---",
    paste0(
      "description: ",
      yaml_quote(paste0("Use when working on FinnTS ", tolower(title), "."))
    ),
    paste0("globs: ", yaml_quote(paste(paths, collapse = ","))),
    "alwaysApply: false",
    "---",
    "",
    paste0("# ", title),
    "",
    paste0(
      "Before changing a matched file, read and follow ",
      "@.claude/rules/", name, "."
    ),
    "",
    "This file is generated by `tools/generate-agent-adapters.R`; do not edit it directly."
  )
}

render_copilot_instructions <- function() {
  c(
    "# FinnTS Repository Instructions",
    "",
    "Follow the canonical repository contract in [AGENTS.md](../AGENTS.md).",
    "Before editing a file, read every matching rule listed in the AGENTS.md instruction map.",
    "Use [.github/agent-guides/validation-matrix.md](agent-guides/validation-matrix.md) to select checks.",
    "",
    "This file is generated by `tools/generate-agent-adapters.R`; do not edit it directly."
  )
}

render_codex_skill <- function(skill_path) {
  skill <- yaml_block(skill_path)
  body <- skill$body
  while (length(body) > 0 && body[[1]] == "") {
    body <- body[-1]
  }

  c(
    "---",
    paste0("name: ", yaml_value(skill$frontmatter, "name", skill_path)),
    paste0(
      "description: ",
      yaml_quote(yaml_value(skill$frontmatter, "description", skill_path))
    ),
    "---",
    "",
    "<!-- Generated from .claude/skills/finnts-validation/SKILL.md. Do not edit directly. -->",
    "",
    body
  )
}

adapter_outputs <- function() {
  rule_files <- list.files(
    ".claude/rules",
    pattern = "\\.md$",
    full.names = TRUE
  )
  if (length(rule_files) == 0) {
    stop("No canonical rules found under .claude/rules.", call. = FALSE)
  }

  outputs <- list(
    ".github/copilot-instructions.md" = render_copilot_instructions(),
    ".agents/skills/finnts-validation/SKILL.md" = render_codex_skill(
      ".claude/skills/finnts-validation/SKILL.md"
    )
  )

  for (rule_file in rule_files) {
    stem <- tools::file_path_sans_ext(basename(rule_file))
    outputs[[paste0(".github/instructions/", stem, ".instructions.md")]] <-
      render_github_rule(rule_file)
    outputs[[paste0(".cursor/rules/", stem, ".mdc")]] <-
      render_cursor_rule(rule_file)
  }

  outputs
}

normalized_text <- function(lines) {
  paste0(paste(lines, collapse = "\n"), "\n")
}

generated_adapter_paths <- function() {
  candidates <- c(
    ".github/copilot-instructions.md",
    list.files(
      ".github/instructions",
      pattern = "\\.instructions\\.md$",
      full.names = TRUE
    ),
    list.files(
      ".cursor/rules",
      pattern = "\\.mdc$",
      full.names = TRUE
    ),
    ".agents/skills/finnts-validation/SKILL.md"
  )
  candidates <- candidates[file.exists(candidates)]
  candidates[vapply(candidates, function(path) {
    any(grepl("generate-agent-adapters.R", read_utf8_lines(path), fixed = TRUE))
  }, logical(1))]
}

write_agent_adapters <- function() {
  outputs <- adapter_outputs()
  obsolete <- setdiff(generated_adapter_paths(), names(outputs))
  if (length(obsolete) > 0) {
    unlink(obsolete)
  }
  for (path in names(outputs)) {
    dir.create(dirname(path), recursive = TRUE, showWarnings = FALSE)
    writeLines(outputs[[path]], path, useBytes = TRUE)
  }
  message("Generated ", length(outputs), " agent compatibility adapters.")
}

check_agent_adapters <- function() {
  outputs <- adapter_outputs()
  missing <- names(outputs)[!file.exists(names(outputs))]
  if (length(missing) > 0) {
    stop("Missing generated adapters: ", paste(missing, collapse = ", "), call. = FALSE)
  }

  stale <- names(outputs)[vapply(names(outputs), function(path) {
    actual <- normalized_text(read_utf8_lines(path))
    expected <- normalized_text(outputs[[path]])
    !identical(actual, expected)
  }, logical(1))]
  if (length(stale) > 0) {
    stop(
      "Stale generated adapters: ", paste(stale, collapse = ", "),
      ". Run Rscript tools/generate-agent-adapters.R.",
      call. = FALSE
    )
  }

  obsolete <- setdiff(generated_adapter_paths(), names(outputs))
  if (length(obsolete) > 0) {
    stop(
      "Obsolete generated adapters: ", paste(obsolete, collapse = ", "),
      ". Run Rscript tools/generate-agent-adapters.R.",
      call. = FALSE
    )
  }

  codex_path <- ".agents/skills/finnts-validation/SKILL.md"
  codex_fields <- sub(
    ":.*$",
    "",
    yaml_block(codex_path)$frontmatter
  )
  unsupported_fields <- setdiff(codex_fields, c("name", "description"))
  if (length(unsupported_fields) > 0) {
    stop(
      codex_path, " contains non-portable frontmatter: ",
      paste(unsupported_fields, collapse = ", "),
      call. = FALSE
    )
  }

  message("Validated ", length(outputs), " generated agent compatibility adapters.")
}

if (sys.nframe() == 0) {
  arguments <- commandArgs(trailingOnly = TRUE)
  if (identical(arguments, "--check")) {
    check_agent_adapters()
  } else if (length(arguments) == 0) {
    write_agent_adapters()
  } else {
    stop("Usage: Rscript tools/generate-agent-adapters.R [--check]", call. = FALSE)
  }
}