on:
  push:
    branches: [main, master]
    tags: ['*']

name: pkgdown

permissions:
  contents: write
  actions: read

jobs:
  pkgdown:
    runs-on: ubuntu-22.04
    env:
      RSPM: https://packagemanager.rstudio.com/cran/__linux__/jammy/latest
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      
      - uses: r-lib/actions/setup-pandoc@465b7d8e732ca3921382b1674c59bada9cbf3399 # v2.13.0

      - uses: r-lib/actions/setup-r@465b7d8e732ca3921382b1674c59bada9cbf3399 # v2.13.0
        with:
          use-public-rspm: true

      - name: Install dependencies
        run: |
          install.packages('remotes')
          install.packages('stringi')
          remotes::install_github("https://github.com/microsoft/finnts")
          install.packages('pkgdown')
          
        shell: Rscript {0}

      - name: Build and deploy pkgdown site
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          Rscript -e 'pkgdown::deploy_to_branch(new_process = FALSE, branch = "gh-pages", github_pages = TRUE)'
